### ISSUE TITLE
Other retailers

### ISSUE THREAD

**Issue by vnglst** [agentcooper/albert-heijn#1]
Hi Artem,

I think it's really cool what you made and that you put this online. I didn't know they had an API and that it's publicly available. I'm thinking about extending this, with price info etc. Would you be interested in cooperating on something like that? 

Do you know if their API is stable (i.e. does the JSON structure remain the same)? 

And do you know of any other publicly available retailer API's, like Jumbo or similar?

Thanks in advance!

**Comment by agentcooper** [comment]
Sorry, missed this.

I can't guarantee anything about this module. This was just some hack I did on a weekend. It seems that the "API" still works though.

No, I did not check other retailers.

**Comment by vnglst** [comment]
No worries, there's no rush. Was working on a side project during the weekend as well. Thanks for your reply!

**Comment by wvengen** [comment]
I've been using their API for more than a year, and it's quite stable - one time the look of the website changed a lot, but the API remained the same.

**Comment by vnglst** [comment]
thanks @wvengen! That's good news. Do you know if there are any other entry points, for instance to get all their product id's?

I created this little demo just last weekend: https://is-het-al-tijd-voor.now.sh/asperges (source: https://github.com/vnglst/is-het-al-tijd-voor). It answers a question that's always on my mind during spring ;-).
