### ISSUE TITLE
Can't access the API?

### ISSUE THREAD

**Issue by JarroVGIT** [agentcooper/albert-heijn#2]
I am trying to fetch the results of the API, but I am trying to build it in C#. 

However, when I try to fetch the following URL, I get a 404. Is the API down or I am missing something very obvious? I took the example URL and encoded it and added it to the REST API URL. I just can't seem te get it working, any thoughts?

https://www.ah.nl/service/rest/delegate?url=https://www.ah.nl/service/rest/delegate?url=https%3A%2F%2Fwww.ah.nl%2Fproducten%2Fproduct%2Fwi33693%2Fah-halfvolle-melk

**Comment by agentcooper** [comment]
@djerro123 
Did you figure it out? Here is the correct link: [`https://www.ah.nl/service/rest/delegate?url=%2Fproducten%2Fproduct%2Fwi33693%2Fah-halfvolle-melk`](https://www.ah.nl/service/rest/delegate?url=%2Fproducten%2Fproduct%2Fwi33693%2Fah-halfvolle-melk).
